---
- name: "Configurar Loopback0 en IOS XE"
  hosts: iosxe
  vars:
    ansible_network_os: cisco.ios.ios
  gather_facts: no
  connection: ansible.netcommon.network_cli
  tasks:
    - name: "Configurar Loopback0 con dirección: 1.1.1.1/32"
      cisco.ios.ios_config:
        lines:
          - "interface loopback0"
          - "ip address 1.1.1.1 255.255.255.255"
