---

- name: "Configurar IOS XE e IOS XR"

  hosts: all

  gather_facts: no
  connection: ansible.netcommon.network_cli

  tasks:

    - name: "Configurar SNMP en IOS XE"

      when: ansible_network_os == 'cisco.ios.ios'
      cisco.ios.ios_config:
        lines:

          - "snmp-server community public RO"

          - "snmp-server contact ruddy@gomez.com"

    - name: "Configurar SNMP en IOS XR"

      when: ansible_network_os == 'iosxr'
      cisco.iosxr.iosxr_config:
        lines:

          - "snmp-server community public RO"

          - "snmp-server contact ruddy@gomez.com"

    - name: "Configurar interfaz Loopback en IOS XE"

      when: ansible_network_os == 'cisco.ios.ios'
      cisco.ios.ios_config:
        lines:

          - "interface loopback0"

          - "ip address 192.168.38.1 255.255.255.0"

    - name: "Configurar interfaz Loopback en IOS XR"

      when: ansible_network_os == 'iosxr'
      cisco.iosxr.iosxr_config:
        lines:

          - "interface Loopback0"

          - "ipv4 address 192.168.14.2 255.255.255.0"
          - "commit"
